const data = [
  {
    status: 1,
    projectName: 'demo',
    projectType: '商业项目',
    task: '任务',
    planHours: 12,
    planPercent: 20,
    planDetail: '细节',
    output: '一个系统',
    result: '结果',
    actualPercent: 23,
    assistStaff: '戴林峰',
    question: '问题',
    time: '2019-07-09',
    actualHours: 6,
    username: '黄龙',
    rejectText: '差劲',
    key: '1152063388721909760',
  },
  {
    status: 1,
    projectName: 'demo',
    projectType: '商业项目',
    task: '任务',
    planHours: 12,
    planPercent: 20,
    planDetail: '细节',
    output: '一个系统',
    actualPercent: 23,
    assistStaff: '戴林峰',
    question: '问题',
    time: '2019-07-09',
    actualHours: 6,
    username: '黄龙',
    rejectText: '差劲',
    key: '1152063388721909761',
  },
  {
    status: 1,
    projectName: 'demo',
    projectType: '商业项目',
    task: '任务',
    planHours: 12,
    planPercent: 20,
    planDetail: '细节',
    output: '一个系统',
    result: '结果',
    actualPercent: 23,
    assistStaff: '戴林峰',
    question: '问题',
    time: '2019-07-09',
    actualHours: 6,
    username: '黄龙',
    rejectText: '差劲',
    key: '1152063388721909762',
  },
  {
    status: 1,
    projectName: 'demo',
    projectType: '商业项目',
    task: '任务',
    planHours: 12,
    planPercent: 20,
    planDetail: '细节',
    output: '一个系统',
    result: '结果',
    actualPercent: 23,
    assistStaff: '戴林峰',
    question: '问题',
    time: '2019-07-09',
    actualHours: 6,
    username: '黄龙',
    rejectText: '差劲',
    key: '1152063388721909763',
  },
  {
    status: 1,
    projectName: 'demo',
    projectType: '商业项目',
    task: '任务',
    planHours: 12,
    planPercent: 20,
    planDetail: '细节',
    output: '一个系统',
    result: '结果',
    actualPercent: 23,
    assistStaff: '戴林峰',
    question: '问题',
    time: '2019-07-09',
    actualHours: 6,
    username: '黄龙',
    rejectText: '差劲',
    key: '1152063388721909764',
  },
  {
    status: 1,
    projectName: 'demo',
    projectType: '商业项目',
    task: '任务',
    planHours: 12,
    planPercent: 20,
    planDetail: '细节',
    output: '一个系统',
    result: '结果',
    actualPercent: 23,
    assistStaff: '戴林峰',
    question: '问题',
    time: '2019-07-09',
    actualHours: 6,
    username: '黄龙',
    rejectText: '差劲',
    key: '1152063388721909765',
  },
  {
    status: 1,
    projectName: 'demo',
    projectType: '商业项目',
    task: '任务',
    planHours: 12,
    planPercent: 20,
    planDetail: '细节',
    output: '一个系统',
    result: '结果',
    actualPercent: 23,
    assistStaff: '戴林峰',
    question: '问题',
    time: '2019-07-09',
    actualHours: 6,
    username: '黄龙',
    rejectText: '差劲',
    key: '1152063388721909766',
  },
  {
    status: 1,
    projectName: 'demo',
    projectType: '商业项目',
    task: '任务',
    planHours: 12,
    planPercent: 20,
    planDetail: '细节',
    output: '一个系统',
    result: '结果',
    actualPercent: 23,
    assistStaff: '戴林峰',
    question: '问题',
    time: '2019-07-09',
    actualHours: 6,
    username: '黄龙',
    rejectText: '差劲',
    key: '1152063388721909767',
  },
  {
    status: 1,
    projectName: 'demo',
    projectType: '商业项目',
    task: '任务',
    planHours: 12,
    planPercent: 20,
    planDetail: '细节',
    output: '一个系统',
    result: '结果',
    actualPercent: 23,
    assistStaff: '戴林峰',
    question: '问题',
    time: '2019-07-09',
    actualHours: 6,
    username: '黄龙',
    rejectText: '差劲',
    key: '1152063388721909768',
  },
  {
    status: 1,
    projectName: 'demo',
    projectType: '商业项目',
    task: '任务',
    planHours: 12,
    planPercent: 20,
    planDetail: '细节',
    output: '一个系统',
    result: '结果',
    actualPercent: 23,
    assistStaff: '戴林峰',
    question: '问题',
    time: '2019-07-09',
    actualHours: 6,
    username: '黄龙',
    rejectText: '差劲',
    key: '1152063388721909769',
  },
  {
    status: 1,
    projectName: 'demo',
    projectType: '商业项目',
    task: '任务',
    planHours: 12,
    planPercent: 20,
    planDetail: '细节',
    output: '一个系统',
    result: '结果',
    actualPercent: 23,
    assistStaff: '戴林峰',
    question: '问题',
    time: '2019-07-09',
    actualHours: 6,
    username: '黄龙',
    rejectText: '差劲',
    key: '1152063388721909770',
  },
];

export default {
  'POST /api/daily/check': { data },
};
